openapi: 3.0.0
info:
  title: RAGFlow API
  description: RESTful APIs for integrating RAGFlow capabilities into third-party
    applications.
  version: 1.0.0
servers:
- url: http://<host_address>/v1/api
security:
- BearerAuth: []
paths:
  /dataset:
    get:
      tags:
      - Dataset
      summary: Get dataset list
      operationId: get_dataset_list
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DatasetListResponse'
      x-openapi-router-controller: swagger_server.controllers.dataset_controller
    post:
      tags:
      - Dataset
      summary: Create dataset
      operationId: create_dataset
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/dataset_body'
        required: true
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DatasetResponse'
      x-openapi-router-controller: swagger_server.controllers.dataset_controller
  /dataset/{dataset_id}:
    get:
      tags:
      - Dataset
      summary: Get dataset details
      operationId: get_dataset_details
      parameters:
      - name: dataset_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DatasetDetailsResponse'
      x-openapi-router-controller: swagger_server.controllers.dataset_controller
    put:
      tags:
      - Dataset
      summary: Update dataset details
      operationId: update_dataset_details
      parameters:
      - name: dataset_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateDatasetRequest'
        required: true
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DatasetDetailsResponse'
      x-openapi-router-controller: swagger_server.controllers.dataset_controller
    delete:
      tags:
      - Dataset
      summary: Delete dataset
      operationId: delete_dataset
      parameters:
      - name: dataset_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
      x-openapi-router-controller: swagger_server.controllers.dataset_controller
  /dataset/{dataset_id}/documents:
    get:
      tags:
      - Documents
      summary: List documents
      operationId: list_documents
      parameters:
      - name: dataset_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: offset
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: integer
      - name: count
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: integer
      - name: order_by
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: descend
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: boolean
      - name: keywords
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListDocumentsResponse'
      x-openapi-router-controller: swagger_server.controllers.documents_controller
    post:
      tags:
      - Documents
      summary: Upload documents
      operationId: upload_documents
      parameters:
      - name: dataset_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/dataset_id_documents_body'
        required: true
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UploadDocumentsResponse'
      x-openapi-router-controller: swagger_server.controllers.documents_controller
  /dataset/{dataset_id}/documents/{document_id}:
    get:
      tags:
      - Documents
      summary: Download document
      operationId: download_document
      parameters:
      - name: dataset_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: document_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Successful response
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
                x-content-type: application/octet-stream
      x-openapi-router-controller: swagger_server.controllers.documents_controller
    put:
      tags:
      - Documents
      summary: Update document details
      operationId: update_document_details
      parameters:
      - name: dataset_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: document_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateDocumentRequest'
        required: true
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentDetailsResponse'
      x-openapi-router-controller: swagger_server.controllers.documents_controller
    delete:
      tags:
      - Documents
      summary: Delete document
      operationId: delete_document
      parameters:
      - name: dataset_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: document_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
      x-openapi-router-controller: swagger_server.controllers.documents_controller
  /dataset/{dataset_id}/documents/{document_id}/parse:
    post:
      tags:
      - Documents
      summary: Start parsing a document
      operationId: start_parsing_document
      parameters:
      - name: dataset_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: document_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
      x-openapi-router-controller: swagger_server.controllers.documents_controller
  /dataset/{dataset_id}/documents/parse:
    post:
      tags:
      - Documents
      summary: Start parsing multiple documents
      operationId: start_parsing_multiple_documents
      parameters:
      - name: dataset_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/documents_parse_body'
        required: true
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
      x-openapi-router-controller: swagger_server.controllers.documents_controller
  /dataset/{dataset_id}/documents/{document_id}/status:
    get:
      tags:
      - Documents
      summary: Show parsing status of document
      operationId: get_document_parsing_status
      parameters:
      - name: dataset_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: document_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentParsingStatusResponse'
      x-openapi-router-controller: swagger_server.controllers.documents_controller
components:
  schemas:
    DatasetResponse:
      type: object
      properties:
        code:
          type: integer
        data:
          $ref: '#/components/schemas/DatasetResponse_data'
        message:
          type: string
      example:
        code: 0
        data:
          dataset_id: dataset_id
          dataset_name: dataset_name
        message: message
    DatasetListResponse:
      type: object
      properties:
        code:
          type: integer
        data:
          type: array
          items:
            $ref: '#/components/schemas/DatasetDetails'
        message:
          type: string
      example:
        code: 0
        data:
        - update_time: 1
          create_time: 6
          name: name
          description: description
          id: id
          created_by: created_by
        - update_time: 1
          create_time: 6
          name: name
          description: description
          id: id
          created_by: created_by
        message: message
    DatasetDetails:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        created_by:
          type: string
        create_time:
          type: integer
        update_time:
          type: integer
      example:
        update_time: 1
        create_time: 6
        name: name
        description: description
        id: id
        created_by: created_by
    DatasetDetailsResponse:
      type: object
      properties:
        code:
          type: integer
        data:
          $ref: '#/components/schemas/DatasetDetails'
        message:
          type: string
      example:
        code: 0
        data:
          update_time: 1
          create_time: 6
          name: name
          description: description
          id: id
          created_by: created_by
        message: message
    UpdateDatasetRequest:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        permission:
          type: string
        language:
          type: string
        chunk_method:
          type: string
        embedding_model_id:
          type: string
        photo:
          type: string
        layout_recognize:
          type: boolean
        token_num:
          type: integer
    UploadDocumentsResponse:
      type: object
      properties:
        code:
          type: integer
        data:
          type: array
          items:
            $ref: '#/components/schemas/DocumentDetails'
        message:
          type: string
      example:
        code: 0
        data:
        - size: 6
          name: name
          location: location
          id: id
          type: type
        - size: 6
          name: name
          location: location
          id: id
          type: type
        message: message
    DocumentDetails:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        location:
          type: string
        size:
          type: integer
        type:
          type: string
      example:
        size: 6
        name: name
        location: location
        id: id
        type: type
    ListDocumentsResponse:
      type: object
      properties:
        code:
          type: integer
        data:
          $ref: '#/components/schemas/ListDocumentsResponse_data'
        message:
          type: string
      example:
        code: 0
        data:
          total: 1
          docs:
          - size: 6
            name: name
            location: location
            id: id
            type: type
          - size: 6
            name: name
            location: location
            id: id
            type: type
        message: message
    UpdateDocumentRequest:
      type: object
      properties:
        name:
          type: string
    DocumentDetailsResponse:
      type: object
      properties:
        code:
          type: integer
        data:
          $ref: '#/components/schemas/DocumentDetails'
        message:
          type: string
      example:
        code: 0
        data:
          size: 6
          name: name
          location: location
          id: id
          type: type
        message: message
    DocumentParsingStatusResponse:
      type: object
      properties:
        code:
          type: integer
        data:
          $ref: '#/components/schemas/DocumentParsingStatusResponse_data'
        message:
          type: string
      example:
        code: 0
        data:
          progress: 6.02745618307040320615897144307382404804229736328125
          status: status
        message: message
    SuccessResponse:
      type: object
      properties:
        code:
          type: integer
        data:
          type: boolean
        message:
          type: string
      example:
        code: 0
        data: true
        message: message
    dataset_body:
      type: object
      properties:
        dataset_name:
          type: string
    dataset_id_documents_body:
      type: object
      properties:
        files:
          type: array
          items:
            type: string
            format: binary
    documents_parse_body:
      type: object
      properties:
        doc_ids:
          type: array
          items:
            type: string
    DatasetResponse_data:
      type: object
      properties:
        dataset_name:
          type: string
        dataset_id:
          type: string
      example:
        dataset_id: dataset_id
        dataset_name: dataset_name
    ListDocumentsResponse_data:
      type: object
      properties:
        docs:
          type: array
          items:
            $ref: '#/components/schemas/DocumentDetails'
        total:
          type: integer
      example:
        total: 1
        docs:
        - size: 6
          name: name
          location: location
          id: id
          type: type
        - size: 6
          name: name
          location: location
          id: id
          type: type
    DocumentParsingStatusResponse_data:
      type: object
      properties:
        progress:
          type: number
        status:
          type: string
      example:
        progress: 6.02745618307040320615897144307382404804229736328125
        status: status
  parameters:
    DatasetId:
      name: dataset_id
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    DocumentId:
      name: document_id
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    Offset:
      name: offset
      in: query
      required: false
      style: form
      explode: true
      schema:
        type: integer
    Count:
      name: count
      in: query
      required: false
      style: form
      explode: true
      schema:
        type: integer
    OrderBy:
      name: order_by
      in: query
      required: false
      style: form
      explode: true
      schema:
        type: string
    Descend:
      name: descend
      in: query
      required: false
      style: form
      explode: true
      schema:
        type: boolean
    Keywords:
      name: keywords
      in: query
      required: false
      style: form
      explode: true
      schema:
        type: string
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      x-bearerInfoFunc: swagger_server.controllers.authorization_controller.check_BearerAuth

